### ISSUE TITLE
Datum der letzten Sitzung herausfinden

### ISSUE THREAD

**Issue by jlauinger** [d120/FsListBot#3]
### Wofür:

Das Datum der letzten Sitzung wird momentan für zwei Dinge benötigt:
- um das letzte Protokoll anzuzeigen (wird an den Wiki-Link angehängt)
- als Voreinstellung für das Datumsfiliterfeld (hier vielleicht eher das Datum der vorletzten Sitzung?
### Ansätze:

Aktuell ist das Datum einfach hartkodiert. Das kann natürlich nicht so bleiben. Vorschläge:
- den letzten Mittwoch nehmen (hat jemand eine Idee wie man das am einfachsten berechnen kann? jQuery und Moment bereits geladen)
- aus dem Wiki den neuesten Protokollartikel parsen. Das könnte ultrahässlich passieren, indem man die Startseite auf DOM-Ebene parst, oder auch indem man den Code aus dem Protokollhelper irgendwie in einem Endpunkt verwendet, der das letzte Datum in JSON ausgibt?
- aus dem Pad extrahieren?
- ...

**Comment by spilot** [comment]
Dieser Vorschlag wird vielleicht alle super geilen Webentwickler unter den Beobachtern zum Lachen bringen, aber kann man nicht einfach™ den body der Seite https://www.fachschaft.informatik.tu-darmstadt.de/wiki/Kategorie:Fachschaftssitzung von unten nach oben nach der Sequenz href="/wiki/Fachschaftssitzung/ durchsuchen? Hinter dem von unten gesehen ersten Auftauchen dieses Strings hat man das Datum in der Form YYYY-MM-DD. Die Seite sollte sich weniger häufig verändern als die Startseite, denn sie wird von MediaWiki automatisch generiert. Außerdem werden dort durch die Protokollvorlage automatisch die Protokolle eingetragen.

**Comment by jlauinger** [comment]
Ja stimmt, das ist zumindest schon mal deutlich weniger hässlich als die Startseite zu parsen

**Comment by bhaettasch** [comment]
Man könnte auch per Google Calendar API auf den entsprechenden Eintrag im Fachschaftskalender zugreifen...

**Comment by luelista** [comment]
@spilot: kann man, zum Beispiel so 
`curl -s 'https://www.fachschaft.informatik.tu-darmstadt.de/wiki/Fachschaftssitzung' | perl -nle 'print $1 if (/Sitzungsprotokoll vom (.{10})/)'`

:smiley:

**Comment by luelista** [comment]
Ich hab mal den letzten Mittwoch berechnet
